# example netlify.toml
[build]
  command = "hugo"
  functions = "functions"
  publish = "public"

  [[redirects]]
    from = "/http4s-jdk-http-client/*"
    to = "https://http4s-jdk-http-client.netlify.com/:splat"
    status = 200
  
  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/netlify-dev-plugin#project-detection
  #[dev] 
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
